<a href="https://colab.research.google.com/github/Arooba10467/AI-Artificial-Intelligence-CSC4101/blob/main/Assighment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nmae: Arooba Afghan
* reg. no.: 2312145
* Assighment 4 (AI Theory)

# Part 1 Home Task

● Unsqueeze()=  this
command returns a new tensor with a dimension of size one inserted at the specific position. it simply mean adding a dimension




In [3]:
import torch

x = torch.tensor([[1, 2, 3], [5, 6, 7]])
print(x.shape)
x

torch.Size([2, 3])


tensor([[1, 2, 3],
        [5, 6, 7]])

In [5]:
x.ndim #dimensions here are 2

2

In [8]:
torch.unsqueeze(x, dim=0)

tensor([[[1, 2, 3],
         [5, 6, 7]]])

In [10]:
torch.unsqueeze(x, dim=1)

tensor([[[1, 2, 3]],

        [[5, 6, 7]]])

In [11]:
torch.unsqueeze(x, dim=2)

tensor([[[1],
         [2],
         [3]],

        [[5],
         [6],
         [7]]])

2. squeeze()

Returns a tensor with all specified dimensions of input of size 1 removed.

In [33]:
y = torch.tensor([[[1, 2, 3],[4,5,6]]])
print(x.shape)  # (1, 3)

y_sq = y.squeeze()
print(y_sq.shape)  # (3,)

torch.Size([2, 3])
torch.Size([2, 3])


In [34]:
y.ndim

3

In [35]:
torch.squeeze(y, dim=0)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
torch.squeeze(y, dim=0).ndim

2

3. tolist()
Convert tensor a multi dimensional array into a → Python list

In [51]:
print("Tensor")
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(type(x))

print("\n Tolist")
y = x.tolist()
print(y)  # [1, 2, 3]
print(type(y))

Tensor
tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>

 Tolist
[[1, 2, 3], [4, 5, 6]]
<class 'list'>


4. tensor.detach()=  is a method in PyTorch that creates a new tensor from an existing tensor but without tracking gradients.

In [54]:
x = torch.tensor([2.0], requires_grad=True)

y = x * 3 # computation tracked
print(y)

z = y.detach() # detached tensor
print(z)

print(y.requires_grad) # true
print(z.requires_grad)  # False


tensor([6.], grad_fn=<MulBackward0>)
tensor([6.])
True
False


neverthless the output are same but the detach is not what the outcome is. its simply stops tracking gradient. so when back track y we find 3 but backtrack z throughs an error


In [59]:
x = torch.tensor([2.0], requires_grad=True)
y = x * 3

# Now, this will work as a fresh graph is created
y.backward()
print(x.grad) # 3.0


tensor([3.])


Detach ctd
* y -> still part of computational graph
*   z -> removed from the graph, no gradient will be computed
*   detach does not change the original tensor.
*   it shares the same data but withoutt gradient tracking
* during inference/ testing we use detach ,
* it saves memory





5. view()
it is a method in PyTorch used to reshape a tensor into a new shape without changing its data.

In [65]:
x = torch.tensor([[1, 2], [3, 4]])
print("Original shape:", x.shape)

y_view = x.view(2,2)
print(y_view)  # [1,2,3,4]

Original shape: torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


data remains same only their arrangement changes.
* the total no of elemts should remaine the same
* either change to (4,)
* or (1,4) or (2,2)
*but not (3,2)


6. clone()

clone() is a method in PyTorch that creates a copy of a tensor with its own separate memory.

In [67]:
x = torch.tensor([1, 2, 3])
y = x.clone()

y[0] = 99
print("x: ", x)  # unchanged
print("y: ", y)

x:  tensor([1, 2, 3])
y:  tensor([99,  2,  3])


7. reshape()

Flexible reshaping

In [68]:
x = torch.tensor([[1, 2], [3, 4]])
x_r = x.reshape(4)

print("original: ", x.shape)
print("reshaped: ", x_r.shape)
print(x_r)

original:  torch.Size([2, 2])
reshaped:  torch.Size([4])
tensor([1, 2, 3, 4])


8. .to()

Move tensor to device (CPU/GPU)

In [69]:
import torch

x = torch.tensor([1, 2, 3])

device = "cuda" if torch.cuda.is_available() else "cpu"

x = x.to(device)

print(x.device)

cpu


# Part 2

● Use pytorch

In [71]:
import torch

In [72]:
import numpy as np
import pandas as pd

● Use Generated dataset from Assignment 3

In [73]:
train_df = pd.read_csv("train_data_A3.csv")
test_df = pd.read_csv("test_data_A3.csv")

X_train = torch.tensor(train_df.iloc[:, :-1].values, dtype=torch.float32)
y_train = torch.tensor(train_df.iloc[:, -1].values, dtype=torch.float32).unsqueeze(1)

X_test = torch.tensor(test_df.iloc[:, :-1].values, dtype=torch.float32)
y_test = torch.tensor(test_df.iloc[:, -1].values, dtype=torch.float32).unsqueeze(1)

● Design a Logistic Regression using Pytorch

In [74]:
input_size = X_train.shape[1]

# weights
w = torch.zeros((input_size, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

● Print model weights before training


In [75]:
print("Initial Weights:", w)
print("Initial Bias:", b)

Initial Weights: tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], requires_grad=True)
Initial Bias: tensor([0.], requires_grad=True)


● Train the model on Generated training data for 10 epochs
* Loss must be printed during training to show how training is gong on

In [79]:
lr = 0.01
epochs = 10

losses = [] # Initialize a list to store losses

for epoch in range(epochs):

    # Forward pass
    z = torch.matmul(X_train, w) + b
    y_pred = torch.sigmoid(z)

    # Loss (Binary Cross Entropy)
    loss = -torch.mean(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred))

    print(f"Epoch {epoch+1}, Loss: {loss.item()}")
    losses.append(loss.item()) # Append the loss to the list

    # Backpropagation
    loss.backward()

    # Update weights
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

    # reset gradients
    w.grad.zero_()
    b.grad.zero_()

Epoch 1, Loss: 0.6931471228599548
Epoch 2, Loss: 0.6917316913604736
Epoch 3, Loss: 0.6903231739997864
Epoch 4, Loss: 0.6889215707778931
Epoch 5, Loss: 0.6875267624855042
Epoch 6, Loss: 0.6861388683319092
Epoch 7, Loss: 0.6847578287124634
Epoch 8, Loss: 0.6833834648132324
Epoch 9, Loss: 0.6820158362388611
Epoch 10, Loss: 0.6806550025939941


● Print new weights


In [80]:
print("Final Weights:", w)
print("Final Bias:", b)

Final Weights: tensor([[ 0.0161],
        [-0.0189],
        [ 0.0228],
        [-0.0114],
        [ 0.0107]], requires_grad=True)
Final Bias: tensor([-0.0009], requires_grad=True)


● Make predictions on testing dataset


In [81]:
with torch.no_grad():
    z = torch.matmul(X_test, w) + b
    y_pred = torch.sigmoid(z)

    y_pred_class = (y_pred >= 0.5).float()

● Evaluate results using Evaluation metric (what evaluation metric we use for logistic
regression)

In [82]:
accuracy = (y_pred_class == y_test).float().mean()

print("Accuracy:", accuracy.item())

Accuracy: 1.0
